services:
  - docker

script:
- docker build -t wilfreddev/source-engine:latest docker-images/source-engine
- docker build -t wilfreddev/java:latest docker-images/java
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master

after_deploy:
- rm -rf /home/travis/.docker/config.json