services:
  - docker

script:
- cd docker-images/source-engine
- docker build -t wilfreddev/source-engine:latest .
- cd .. && cd java
- docker build -t wilfreddev/java:latest .
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master

after_deploy:
- rm -rf /home/travis/.docker/config.json